/*
 * VentanaPrincipal.java
 *
 * Created on 21 de agosto de 2008, 12:02
 */

package vista;





/**
 *
 * @author  marcelo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() 
    {
        initComponents();
        
//        VentanaPrincipalImg panel = new VentanaPrincipalImg();
//        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("imagenes/esquema.jpg"));
//        Panel panel = new Panel();
//        this.add(panel);
//        this.pack();
        this.setLocation(0, 20);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSensores = new javax.swing.ButtonGroup();
        panel1 = new vista.Panel();
        jRadioButtonPuerta1 = new javax.swing.JRadioButton();
        jRadioButtonLiving = new javax.swing.JRadioButton();
        jRadioButtonSalaEstar = new javax.swing.JRadioButton();
        jRadioButtonCocina = new javax.swing.JRadioButton();
        jRadioButtonPuerta2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setResizable(false);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/esquema.jpg"))); // NOI18N

        jRadioButtonPuerta1.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonPuerta1);

        jRadioButtonLiving.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonLiving);

        jRadioButtonSalaEstar.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonSalaEstar);

        jRadioButtonCocina.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonCocina);

        jRadioButtonPuerta2.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonPuerta2);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonPuerta1)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonLiving)
                        .addGap(146, 146, 146))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jRadioButtonSalaEstar)
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jRadioButtonCocina)
                .addContainerGap(492, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(jRadioButtonPuerta2)
                .addGap(47, 47, 47))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jRadioButtonCocina)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonPuerta1)
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonPuerta2)
                .addGap(52, 52, 52)
                .addComponent(jRadioButtonSalaEstar)
                .addGap(16, 16, 16)
                .addComponent(jRadioButtonLiving)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSensores;
    private javax.swing.JRadioButton jRadioButtonCocina;
    private javax.swing.JRadioButton jRadioButtonLiving;
    private javax.swing.JRadioButton jRadioButtonPuerta1;
    private javax.swing.JRadioButton jRadioButtonPuerta2;
    private javax.swing.JRadioButton jRadioButtonSalaEstar;
    private vista.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
