/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIReporteTest.java
 *
 * Created on 27/05/2010, 02:15:10
 */

package vista;

import evaluadores.TestIndependencia;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Vector;
import vista.util.UIReporteTestUtil;

/**
 *
 * @author marcelo
 */
public class UIReporteTest extends javax.swing.JFrame
{

    private TestIndependencia testIndependencia = new TestIndependencia();
    private Vector numeros = new Vector();
    private UIReporteTestUtil util = new UIReporteTestUtil();

    /** Creates new form UIReporteTest */
    public UIReporteTest() {
        initComponents();
        this.inicializar();
    }

    public UIReporteTest(Vector numeros)
    {
        this.numeros = numeros;
        initComponents();
        this.inicializar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResultadoTestIndependencia = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaResultadoTestCiclo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Test");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Test de Independencia"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaResultadoTestIndependencia.setBackground(new java.awt.Color(231, 190, 124));
        jTextAreaResultadoTestIndependencia.setColumns(20);
        jTextAreaResultadoTestIndependencia.setLineWrap(true);
        jTextAreaResultadoTestIndependencia.setRows(5);
        jTextAreaResultadoTestIndependencia.setDisabledTextColor(new java.awt.Color(8, 6, 6));
        jTextAreaResultadoTestIndependencia.setEnabled(false);
        jTextAreaResultadoTestIndependencia.setOpaque(false);
        jScrollPane1.setViewportView(jTextAreaResultadoTestIndependencia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Test de Ciclos"));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaResultadoTestCiclo.setBackground(new java.awt.Color(231, 190, 124));
        jTextAreaResultadoTestCiclo.setColumns(20);
        jTextAreaResultadoTestCiclo.setLineWrap(true);
        jTextAreaResultadoTestCiclo.setRows(5);
        jTextAreaResultadoTestCiclo.setDisabledTextColor(new java.awt.Color(8, 6, 6));
        jTextAreaResultadoTestCiclo.setEnabled(false);
        jTextAreaResultadoTestCiclo.setOpaque(false);
        jScrollPane2.setViewportView(jTextAreaResultadoTestCiclo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIReporteTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaResultadoTestCiclo;
    private javax.swing.JTextArea jTextAreaResultadoTestIndependencia;
    // End of variables declaration//GEN-END:variables

    private void inicializar()
    {
        this.centrar();
        this.mostrarTestIndependencia();
        this.mostrarTestCiclo();

    }

    private void centrar()
    {
        Dimension pantalla, cuadro;
	pantalla = Toolkit.getDefaultToolkit().getScreenSize();
	cuadro = this.getSize();
	this.setLocation(((pantalla.width - cuadro.width)/2), (pantalla.height - cuadro.height)/2);
    }

    private void mostrarTestIndependencia()
    {
        this.jTextAreaResultadoTestIndependencia.setText(this.testIndependencia.test(this.numeros));
    }

    private void mostrarTestCiclo()
    {
        this.util.testCiclo(jTextAreaResultadoTestCiclo, numeros);
    }

}
