/*
 * VentanaPrincipal.java
 *
 * Created on 21 de agosto de 2008, 12:02
 */

package habstraccionhardware;

import vista.VentanaNuevaMusica;
import vista.VentanaNuevoAlimento;
import vista.VentanaNuevoCanal;
import vista.VentanaNuevoContenedor;
import vista.VentanaNuevoContexto;
import vista.VentanaNuevoEstadoAnimo;





/**
 *
 * @author  marcelo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() 
    {
        initComponents();
        
//        VentanaPrincipalImg panel = new VentanaPrincipalImg();
//        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("imagenes/esquema.jpg"));
//        Panel panel = new Panel();
//        this.add(panel);
//        this.pack();
        this.setLocation(0, 20);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSensores = new javax.swing.ButtonGroup();
        panel1 = new vista.Panel();
        jRadioButtonPuerta1 = new javax.swing.JRadioButton();
        jRadioButtonLiving = new javax.swing.JRadioButton();
        jRadioButtonSalaEstar = new javax.swing.JRadioButton();
        jRadioButtonCocina = new javax.swing.JRadioButton();
        jRadioButtonPuerta2 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAdministracion = new javax.swing.JMenu();
        jMenuItemTema = new javax.swing.JMenuItem();
        jMenuItemCanal = new javax.swing.JMenuItem();
        jMenuItemEstadoAnimo = new javax.swing.JMenuItem();
        jMenuItemAlimentos = new javax.swing.JMenuItem();
        jMenuItemContenedor = new javax.swing.JMenuItem();
        jMenuItemContexto = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setResizable(false);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/esquema.jpg"))); // NOI18N

        jRadioButtonPuerta1.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonPuerta1);

        jRadioButtonLiving.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonLiving);

        jRadioButtonSalaEstar.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonSalaEstar);

        jRadioButtonCocina.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonCocina);

        jRadioButtonPuerta2.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroupSensores.add(jRadioButtonPuerta2);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonPuerta1)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonLiving)
                        .addGap(146, 146, 146))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jRadioButtonSalaEstar)
                .addContainerGap(423, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(711, Short.MAX_VALUE)
                .addComponent(jRadioButtonPuerta2)
                .addGap(47, 47, 47))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jRadioButtonCocina)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jRadioButtonCocina)
                .addGap(32, 32, 32)
                .addComponent(jRadioButtonPuerta1)
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonPuerta2)
                .addGap(52, 52, 52)
                .addComponent(jRadioButtonSalaEstar)
                .addGap(16, 16, 16)
                .addComponent(jRadioButtonLiving)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jMenuAdministracion.setText("Administracion");

        jMenuItemTema.setText("Tema Musical ...");
        jMenuItemTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTemaActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemTema);

        jMenuItemCanal.setText("Canal de Television ...");
        jMenuItemCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCanalActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemCanal);

        jMenuItemEstadoAnimo.setText("Estado de Animo..");
        jMenuItemEstadoAnimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoAnimoActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemEstadoAnimo);

        jMenuItemAlimentos.setText("Alimentos...");
        jMenuItemAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlimentosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemAlimentos);

        jMenuItemContenedor.setText("Contenedor...");
        jMenuItemContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContenedorActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemContenedor);

        jMenuItemContexto.setText("Contextos...");
        jMenuItemContexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContextoActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(jMenuItemContexto);

        jMenuBar1.add(jMenuAdministracion);

        jMenuAyuda.setText("Ayuda");

        jMenuItem1.setText("Ver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTemaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemTemaActionPerformed
    {//GEN-HEADEREND:event_jMenuItemTemaActionPerformed
        // TODO add your handling code here:
        VentanaNuevaMusica nuevaMusica = new VentanaNuevaMusica();
        nuevaMusica.setVisible(true);
    }//GEN-LAST:event_jMenuItemTemaActionPerformed

    private void jMenuItemCanalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemCanalActionPerformed
    {//GEN-HEADEREND:event_jMenuItemCanalActionPerformed
        // TODO add your handling code here:
        VentanaNuevoCanal nuevoCanal = new VentanaNuevoCanal();
        nuevoCanal.setVisible(true);
    }//GEN-LAST:event_jMenuItemCanalActionPerformed

    private void jMenuItemEstadoAnimoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemEstadoAnimoActionPerformed
    {//GEN-HEADEREND:event_jMenuItemEstadoAnimoActionPerformed
        // TODO add your handling code here:
        VentanaNuevoEstadoAnimo nuevoEstadoAnimo = new VentanaNuevoEstadoAnimo();
        nuevoEstadoAnimo.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstadoAnimoActionPerformed

    private void jMenuItemAlimentosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemAlimentosActionPerformed
    {//GEN-HEADEREND:event_jMenuItemAlimentosActionPerformed
        // TODO add your handling code here:
        VentanaNuevoAlimento nuevoAlimento = new VentanaNuevoAlimento();
        nuevoAlimento.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlimentosActionPerformed

    private void jMenuItemContenedorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemContenedorActionPerformed
    {//GEN-HEADEREND:event_jMenuItemContenedorActionPerformed
        // TODO add your handling code here:
        VentanaNuevoContenedor nuevoContenedor = new VentanaNuevoContenedor();
        nuevoContenedor.setVisible(true);
    }//GEN-LAST:event_jMenuItemContenedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemContextoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemContextoActionPerformed
    {//GEN-HEADEREND:event_jMenuItemContextoActionPerformed
        // TODO add your handling code here:
        VentanaNuevoContexto nuevoContexto = new VentanaNuevoContexto();
        nuevoContexto.setVisible(true);
    }//GEN-LAST:event_jMenuItemContextoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSensores;
    private javax.swing.JMenu jMenuAdministracion;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAlimentos;
    private javax.swing.JMenuItem jMenuItemCanal;
    private javax.swing.JMenuItem jMenuItemContenedor;
    private javax.swing.JMenuItem jMenuItemContexto;
    private javax.swing.JMenuItem jMenuItemEstadoAnimo;
    private javax.swing.JMenuItem jMenuItemTema;
    private javax.swing.JRadioButton jRadioButtonCocina;
    private javax.swing.JRadioButton jRadioButtonLiving;
    private javax.swing.JRadioButton jRadioButtonPuerta1;
    private javax.swing.JRadioButton jRadioButtonPuerta2;
    private javax.swing.JRadioButton jRadioButtonSalaEstar;
    private vista.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
